config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#explore"
  resources :communities, param: :identifier
  resources :datasets

  get 'profile' => 'profiles#show', as: 'show_profile'
  get 'communities/:identifier/join' => 'communities#join', as: 'join_community'

  get 'communities/:identifier/members' => 'communities#members', as: 'community_members'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
    format: { with: /\A[A-Za-z0-9\-\_]+\z/,
      message: "only allows letters" }
  validates :description, presence: true
  has_many :memberships
  has_many :users, through: :memberships
  has_many :datasets

  def to_param
    name
  end
end

app/models/dataset.rb
class Dataset < ApplicationRecord
  mount_uploader :datafile, DatafileUploader
  belongs_to :user
  belongs_to :community
  validates :name, presence: true, uniqueness: true
  validates :documentation, :user, :community, presence: true
  validates :private, inclusion: { in: [ true, false ] }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :omniauthable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :datasets
  has_many :memberships
  has_many :communities, through: :memberships

  def create_community(name, description)
    community = Community.new(name: name, description: description)
    self.memberships.create(community: community)
    community.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :login

  def login
    @user = User.new
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end
 
  def show
    @community = Community.find_by(name: params[:identifier])
  end

  def members
    @community = Community.find_by(name: params[:identifier])
  end
 
  def new
    @community = Community.new
  end

  def join
    @community = Community.find_by(name: params[:identifier])
    current_user.memberships.create(community: @community)
    redirect_to @community
  end
 
  def edit
    @community = Community.find_by(name: params[:identifier])
  end
 
  def create
    @community = Community.new(community_params)

    if current_user
      current_user.memberships.create(community: @community)
    else
      render redirect_to '/users/sign_in'
    end
 
    if @community.save
      redirect_to @community
    else
      render 'new'
    end
  end
 
  def update
    @community = Community.find_by(name: params[:identifier])
 
    if @community.update(community_params)
      redirect_to @community
    else
      render 'edit'
    end
  end
 
  def destroy
    @community = Community.find_by(name: params[:identifier])
    @community.destroy
 
    redirect_to communities_path
  end
 
  private
    def community_params
      params.require(:community).permit(:name, :description)
    end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  def index
    @datasets = Dataset.all
  end
 
  def show
    @dataset = Dataset.find(params[:id])
  end
 
  def new
    @dataset = Dataset.new
  end
 
  def edit
    @dataset = Dataset.find(params[:id])
  end
 
  def create
    @dataset = Dataset.new(dataset_params)
    community = Community.find_by_name(params[:community_name])
    @dataset.community = community

    if current_user
      @dataset.user = current_user
    else
      render redirect_to '/users/sign_in'
    end
 
    if @dataset.save
      redirect_to @dataset
    else
      render 'new'
    end
  end
 
  def update
    @dataset = Dataset.find(params[:id])
    community = Community.find_by_name(params[:community_name])
    @dataset.community = community
 
    if @dataset.update(dataset_params)
      redirect_to @dataset
    else
      render 'edit'
    end
  end
 
  def destroy
    @dataset = Dataset.find(params[:id])
    @dataset.destroy
 
    redirect_to datasets_path
  end
 
  private
    def dataset_params
      params.require(:dataset).permit(:name, :documentation, :private, :datafile)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def login
  end

  def explore
    @user = User.new
    @communities = Community.all
    @datasets = Dataset.all

    @entries = @communities + @datasets
    @entries.shuffle!
  end

  def dataset
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    html = markdown.render("This is *bongos*, indeed." * 100)
    @dataset = { name: 'Dataset Name', documentation: html, date_published: 'July 10, 2017', author: 'Je Marie Apolinario' }
  end

  def new_dataset
  end

  def update_dataset
  end

  def new_community
  end

  def community_datasets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/dataset_helper.rb
module DatasetHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/communities/members.html.erb
<div class="ui grid" id="community-page">
    <div class="row">
        <div class="sixteen wide column">
            <h5 class="ui header"><%= @community.name %></h5>
            <div class="ui divider"></div>
            <div class="ui message">
                <%= @community.description %>
            </div>
            <div class="ui secondary pointing two item menu">
                <%= link_to('Datasets', @community, class: 'item') %>  
                <%= link_to('Members', community_members_path(@community), class: 'active item') %>  

            </div>

			  <div class="ui grid">

              <% @community.users.each do |user| %>
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                    <img class="left floated mini ui image" src="https://api.adorable.io/avatars/285/user.png" style="margin-top: 5px;">
                    <div class="header">
                    <b><%= user.name %></b>
                    </div>
                    <div class="meta">
                        <%= user.email %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/communities/new.html.erb
<div class="ui basic segment">


    <h2 class="ui header">Create a Community</h2>
    <div class="ui divider"></div>
    <%= form_for @community, html: { class: 'ui form' } do |f| %>

        <div class="field">
            <label>Name of Community:</label>
            <%= f.text_field :name, placeholder: 'Name of Community' %>

        </div>
        <div class="field">
            <label>Description:</label>
            <%= f.text_area :description, placeholder: 'Description'%>
        </div>
        <%= f.submit "Create Community", class: "ui button primary" %>

    <% end %>
</div>

app/views/communities/show.html.erb
<div class="ui grid" id="community-page">
    <div class="row">
        <div class="sixteen wide column">
            
            <h5 class="ui header"><%= @community.name %>
                <% if user_signed_in? and not current_user.communities.include?(@community) %>
                <%= link_to '+ Join Community', join_community_path, class: 'ui label tiny blue'%>
                <%end%>
            </h5>
            <div class="ui divider"></div>
            <div class="ui message">
                <%= @community.description %>
            </div>
            <div class="ui secondary pointing two item menu">
                <%= link_to('Datasets', @community, class: 'active item') %>  
				<%= link_to('Members', community_members_path(@community), class: 'item') %>  

            </div>

			<% @community.datasets.each do |dataset| %>
            <%= link_to dataset, :class => 'ui card fluid' do %>
                <div class="content">
			    	<div href='#' class="header"><%= dataset.name %></div>
			    	<div class="meta">by <%= dataset.user.name %></div>
			    	<div class="description">
			        	<%= dataset.documentation %>
			    	</div>
			    </div>
            <%end %>
			<% end %>
        </div>
    </div>
</div>

app/views/datasets/_form.html.erb
<%= form_with model: @dataset, local: true, html: {multipart: true, class: 'ui form'} do |form| %>
 
  <% if @dataset.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@dataset.errors.count, "error") %> prohibited
        this dataset from being saved:
      </h2>
      <ul>
        <% @dataset.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form_for @dataset, html: { multipart: true } do |f| %>
    <div class="field">
            <form>
            <label>Community</label>
            <div class="ui selection dropdown">
                <input type="hidden" name="community_name">
                <i class="dropdown icon"></i>
                <% if @dataset.community %>
                <div class="default text"><%= @dataset.community.name %></div>
                <% else %>
                <div class="default text">Community</div>
                <% end %>                
                <div class="menu">
                    <% current_user.communities.each do |community| %>
                    <div class="item" data-value="<%=community.name%>"><%= community.name %></div>
                    <% end %>
                </div>
            </div>
            <form>
        </div>
        <div class="field">
            <label>Name of Dataset:</label>
            <%= f.text_field :name, placeholder: 'Name of Dataset' %>
        </div>
        <div class="field">
            <label>Documentation:</label>
            <%= f.text_area :documentation %>
            <h6 class="ui header">*Markdown is supported</h6>
        </div>
        <div class="field">
            <div class="ui toggle checkbox">
                <%= f.check_box :private, class: 'hidden' %>
                <label>Make Dataset Private</label>
            </div>
        </div>
        <div class="field">
            <label>Upload CSV File:</label>
            <%= f.file_field :datafile %>
        </div>
        <%= f.submit "Upload Dataset", class: "ui button primary" %>
  <% end %>
 
<% end %>

app/views/datasets/edit.html.erb
<h2 class="ui header">Update Dataset</h2>
    <div class="ui divider"></div>
 
<%= render 'form' %>

app/views/datasets/index.html.erb
<h1>Listing datasets</h1>
<%= link_to 'New dataset', new_dataset_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Documentation</th>
    <th colspan="3"></th>
  </tr>
 
  <% @datasets.each do |dataset| %>
    <tr>
      <td><%= dataset.name %></td>
      <td><%= dataset.documentation %></td>
      <td><%= link_to 'Show', dataset_path(dataset) %>|</td>
      <td><%= link_to 'Edit', edit_dataset_path(dataset) %>|</td>
      <td><%= link_to 'Destroy', dataset_path(dataset),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/datasets/new.html.erb
<div class="ui basic segment" id="new-dataset">
    <h2 class="ui header">Upload Dataset</h2>
    <div class="ui divider"></div>
   
    <%= render 'form' %>
</div>

app/views/datasets/show.html.erb
<div class="ui basic segment" id="dataset">
    <div class="ui breadcrumb">
        <%= link_to @dataset.community.name, @dataset.community, class: 'section' %>
        <i class="right angle icon divider"></i>
        <div class="active section"><%= @dataset.name %></div>
    </div>
    <div class="ui divider"></div>

    <h2 class="ui header"><%= @dataset.name %> 
        <% if @dataset.private %>
        <span><i class="icon lock"></i></span>
        <% end %>
        <div class="sub header">Author: <%= @dataset.user.name %></div>
        <div class="sub header">Date published: <%= @dataset.created_at %></div>
        <div class="sub header">Last updated: <%= @dataset.updated_at %></div>
    </h2>

    <%= link_to @dataset.datafile.url, :class => 'ui button green mini' do %>
    <i class="icon download"></i> Download CSV File
    <% end %>
    <% if user_signed_in? and current_user.datasets.include?(@dataset) %>
    <%= link_to edit_dataset_path(@dataset), :class => 'ui button blue mini' do %>
    <i class="icon write"></i> Update Dataset
    <% end %>
    <% end %>
    <div class="ui message">
        <p><%= @dataset[:documentation].html_safe %></p>
    </div>

    <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://datum-2.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datum</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <div class="break"></div>
    <div class="ui grid container">
      <% if user_signed_in? %>
        <div class="three wide column">
            <%= render 'shared/sidebar' %>
        </div>
        <div class="thirteen wide column">
            <%= yield %>
          <div class="ui divider"></div>
        </div>
      <% else %>
        <div class="sixteen wide column">
            <%= yield %>
          <div class="ui divider"></div>
            
        </div>
      <% end %>
    </div>  
    <script>
      $(document).ready(function(){
          $('.ui.dropdown').dropdown();

          $('.ui.checkbox')
          .checkbox()
        ;
      });
    </script>
  </body>
</html>

app/views/profiles/show.html.erb
<div class="ui image tiny circular"><img src="https://api.adorable.io/avatars/285/user.png" alt=""></div>
<h2 class="ui header"><%= current_user.name %> <span><i class="icon check circle green"></i></span> 
    <div class="sub header"><%= current_user.email %></div>
</h2>
<div class="ui divider"></div>

<h3 class="ui header">Occupation: </h3> <span>Professor in UP Diliman</span>
<h3 class="ui header">Field of Interests: </h3><span>Networks and Distributed Systems</span>
<h3 class="ui header">Educational Background: </h3><span>PhD in Memes Creation Major in Dank Memes</span>

<h2 class="ui header">List of Datasets Contributed</h3>
<div class="ui divider"></div>
<% current_user.datasets.each do |dataset| %>
<%= link_to dataset, :class => 'ui card fluid' do %>
    <div class="content">
        <div href='#' class="header"><%= dataset.name %></div>
        <div class="meta">by <%= dataset.user.name %></div>
        <div class="description">
            <%= dataset.documentation %>
        </div>
    </div>
<%end %>
<% end %>

app/views/shared/_community_page.html.erb
<div class="ui grid" id="community-page">
    <div class="row">
        <div class="sixteen wide column">
            <h5 class="ui header">TransparencyPH</h5>
            <div class="ui divider"></div>
                <div class="ui message">
                  <p>Transparency Ph is a non-stock, non-profit, public benefit student-run organization that aims to provide online access to government information available to anyone, anywhere, and at no cost.</p>
                </div>
            <div class="ui secondary pointing two item menu">
                <a href="#" class="active item">Datasets</a>
                <a href="#" class="item">Members</a>
            </div>
        </div>
    </div>
</div>

app/views/shared/_explore-featured.html.erb
<div class="ui container fluid" id="explore-featured">
    <div class="ui container basic segment">
        <div class="ui two cards link">
            <div class="card" style="height: 250px;"></div>
            <div class="card" style="height: 250px;"></div>
        </div>
    </div>
</div>

app/views/shared/_explore.html.erb
<div class="ui basic grid segment" id="explore">
    <div class="two column row">
        <div class="column">
            <h2 class="ui header">Explore</h2>
        </div>
        <div class="column right aligned">
            <div class="ui search large">
                <div class="ui icon input">
                    <input class="prompt" type="text" placeholder="Communities/Datasets">
                    <i class="search icon"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="sixteen wide column">
            <div class="ui cards two link">
                <div class="card featured"></div>
                <div class="card featured"></div>
            </div>
            <div class="ui cards four link">
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
                <div class="card"></div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_members.html.erb
<!-- <div class="ui basic grid segment" id="members"> -->

    <div class="two column row">
        <div class="column">
            <h2 class="ui header" style="margin-top:5px;">Members</h2>
        </div>
        <div class="column"></div>
    </div>



    <div class="ui grid">
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                    <img class="left floated mini ui image" src="<%= asset_path('icon1.jpg')%>" style="margin-top: 5px;">
                    <div class="header">
                    <b>Elliot Cornelius</b>
                    </div>
                    <div class="meta">
                        elliot_654
                    </div>
                    <div class="description" style="font-size:75%;">
                        Member since September 2014
                    </div>
                </div>
            </div>
        </div>
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                        <img class="left floated mini ui image" src="<%= asset_path('icon2.jpg')%>" style="margin-top: 5px;">
                        <div class="header">
                        <b>Jenny Eisenberg</b>
                        </div>
                        <div class="meta">
                            jenny.eisenberg1179
                        </div>
                        <div class="description" style="font-size:75%;">
                            Member since August 2016
                        </div>
                    </div>
                </div>
            </div>
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                    <img class="left floated mini ui image" src="<%= asset_path('icon1.jpg')%>" style="margin-top: 5px;">
                    <div class="header">
                    <b>Elliot Cornelius</b>
                    </div>
                    <div class="meta">
                        elliot_654
                    </div>
                    <div class="description" style="font-size:75%;">
                        Member since September 2014
                    </div>
                </div>
            </div>
        </div>
        <div class="one wide column"></div>
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                        <img class="left floated mini ui image" src="<%= asset_path('icon2.jpg')%>" style="margin-top: 5px;">
                        <div class="header">
                        <b>Jenny Eisenberg</b>
                        </div>
                        <div class="meta">
                            jenny.eisenberg1179
                        </div>
                        <div class="description" style="font-size:75%;">
                            Member since August 2016
                        </div>
                    </div>
                </div>
            </div>
        <div class="one wide column"></div>
        <div class="four wide column">
            <div class="segment">
                <div class="content">
                    <img class="left floated mini ui image" src="<%= asset_path('icon1.jpg')%>" style="margin-top: 5px;">
                    <div class="header">
                    <b>Elliot Cornelius</b>
                    </div>
                    <div class="meta">
                        elliot_654
                    </div>
                    <div class="description" style="font-size:75%;">
                        Member since September 2014
                    </div>
                </div>
            </div>
        </div>
        <div class="one wide column"></div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="ui fixed menu borderless" id="navbar">
    <div class="ui container">
        <%= link_to root_path, :class => 'item' do%>
            <img src="<%= asset_url('logo.png') %>" alt="logo">
        <% end %>
        <%# <a href="#" class="item">Datasets</a> %>
        <div class="right menu">
            <% if not user_signed_in? %>
            <div class="item">
                <%= form_for(@user, :url => session_path(@user), :html => {class: "ui form", id: "login"}) do |f| %>
                <div class="fields">
                    <div class="field">
                        <div class="ui input">
                            <%= f.email_field :email, autofocus: true, placeholder: "Email" %>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui input">
                            <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
                        </div>
                    </div>
                    <div class="field">
                        <%= f.submit "Login", class: "ui button primary", id: "login_button" %>
                    </div>
                </div>
                <% end %>
            </div>
            <% else %>
            <%= link_to new_dataset_path, :class => 'item' do%>
            <button class="ui button primary small"><i class="icon upload"></i>Upload Dataset</button>
            <% end %>
            <div class="ui dropdown item">
                <img class="ui avatar image" src="https://api.adorable.io/avatars/285/user.png">
                <span> <%= current_user.name %> <i class="icon down angle down"></i></span>
                <div class="menu">
                <%= link_to('Profile', show_profile_path, class: 'item') %>  
                <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'item', id: 'logout_button') %>  
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="ui secondary vertical menu" id="sidebar">
    <div class="header item">COMMUNITIES</div>
    <% current_user.communities.each do |community| %>
    <%= link_to(community.name, community, class: 'item') %>  
    <% end %>
</div>
<%= link_to 'Create a community', new_community_path, class: 'ui button primary tiny'%>

app/views/static_pages/community_datasets.html.erb
<div class="ui grid" id="community-page">
    <div class="row">
        <div class="sixteen wide column">
            <h5 class="ui header">TransparencyPH</h5>
            <div class="ui divider"></div>
            <div class="ui message">
                Lorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem IpsumLorem Ipsum
            </div>
            <div class="ui secondary pointing two item menu">
                <a href="#" class="active item">Datasets</a>
                <a href="#" class="item">Members</a>
            </div>

			<div href='#' class="ui card link fluid">
			    <div class="content">
			    	<a href='#' class="header">Epidemiology of the Philippine Barangays</a>
			    	<div class="meta">by Je Marie Apolinario and Camille Razal</div>
			    	<div class="description">
			        	This contains the epidemiology of the Philippine Barangays from years 2000-2015. This dataset is used for a Web Science undergraduate thesis using Quantum Geographical Information Systems for spatial data analysis.
			    	</div>
			    	<br><span class="meta">Tags:</span>
			      	<a class="tiny ui label">
			      		Epidemiology
					</a>
						<a class="tiny ui label">
			      		Barangays
					</a>
			    </div>
			</div>
			<div href='#' class="ui card link fluid">
			    <div class="content">
			    	<a href='#' class="header">Epidemiology of the Philippine Barangays</a>
			    	<div class="meta">by Je Marie Apolinario and Camille Razal</div>
			    	<div class="description">
			        	This contains the epidemiology of the Philippine Barangays from years 2000-2015. This dataset is used for a Web Science undergraduate thesis using Quantum Geographical Information Systems for spatial data analysis.
			    	</div>
			    	<br><span class="meta">Tags:</span>
			      	<a class="tiny ui label">
			      		Epidemiology
					</a>
						<a class="tiny ui label">
			      		Barangays
					</a>
			    </div>
			</div>
			<div href='#' class="ui card link fluid">
			    <div class="content">
			    	<a href='#' class="header">Epidemiology of the Philippine Barangays</a>
			    	<div class="meta">by Je Marie Apolinario and Camille Razal</div>
			    	<div class="description">
			        	This contains the epidemiology of the Philippine Barangays from years 2000-2015. This dataset is used for a Web Science undergraduate thesis using Quantum Geographical Information Systems for spatial data analysis.
			    	</div>
			    	<br><span class="meta">Tags:</span>
			      	<a class="tiny ui label">
			      		Epidemiology
					</a>
						<a class="tiny ui label">
			      		Barangays
					</a>
			    </div>
			</div>
        </div>
    </div>
</div>

app/views/static_pages/dashboard.html.erb
<%= render 'shared/navbar' %>
<div class="break"></div>
<div class="ui grid container">
    <div class="three wide column">
        <%= render 'shared/sidebar' %>
    </div>
    <div class="thirteen wide column">
        <%= render 'shared/community_page' %>
<!--         <%= render 'shared/explore' %> -->
        <%= render 'shared/members' %>
    </div>
</div>  

app/views/static_pages/dataset.html.erb
<div class="ui basic segment" id="dataset">
    <div class="ui breadcrumb">
        <a class="section">Community</a>
        <i class="right angle icon divider"></i>
        <div class="active section"><%= @dataset[:name] %></div>
    </div>
    <div class="ui divider"></div>

    <h2 class="ui header"><%= @dataset[:name] %> 
        <% if @dataset.private %>
        <span><i class="icon lock"></i></span>
        <% end %>
        <div class="sub header">Author: <%= @dataset[:author] %></div>
        <div class="sub header">Date published: <%= @dataset[:date_published] %></div>
        <div class="sub header">Last updated: <%= @dataset[:date_published] %></div>
    </h2>
    <button class="ui button green mini"><i class="icon download"></i> Download CSV File</button>
    <% if true %>
    <button class="ui button blue mini"><i class="icon write"></i> Update Dataset</button>
    <% end %>
    <div class="ui message">
        <p><%= @dataset[:documentation].html_safe %></p>
    </div>

    .
</div>

app/views/static_pages/login.html.erb
<div class="ui grid container middle aligned">
    <div class="three column row">
        <div class="column centered">
            <div class="ui segment" id="login">
                <div class="ui form">
                    <div class="field">
                        <label>Email</label>
                        <input type="text" name="email" placeholder="Email">
                    </div>
                    <div class="field">
                        <label>Password</label>
                        <input type="password" name="password" placeholder="Password">
                    </div>
                    <button class="ui primary button centered" type="submit">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/new_community.html.erb
<div class="ui basic segment">


    <h2 class="ui header">Create a Community</h2>
    <div class="ui divider"></div>
    <form action="post" class="ui form">

        <div class="field">
            <label>Name of Community:</label>
            <input type="text" name="name" placeholder="Name of Community">
        </div>
        <div class="field">
            <label>Description:</label>
            <textarea></textarea>
        </div>
        <div class="field">
            <label>Upload CSV File:</label>
            <input type="file" name="csv">
        </div>
        <button class="ui button primary">Submit Data</button>
    </form>
</div>